=== npiccolotto/undrground-tubes/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://example.com/product.schema.json",
  "title": "ESVis Input",
  "description": "A valid ESVis input",
  "type": "object",
  "required": [
    "S",
    "E",
    "EA",
    "SR"
  ],
  "properties": {
    "glyph_ids": {
      "description": "paths to glyph images. i-th entry holds image for i-th element.",
      "type": "array"
    },
    "E": {
      "description": "labels for elements",
      "type": "array"
    },
    "EA": {
      "description": "distance matrix (list of list) for element data",
      "type": "array"
    },
    "SA": {
      "description": "distance matrix (list of list) for set data",
      "type": "array"
    },
    "SR": {
      "description": "set relations, as list of list. i-th entry holds sets that element i belongs to. ",
      "type": "array"
    },
    "S": {
      "description": "labels for sets",
      "type": "array"
    },
    "SC": {
      "description": "colors for sets in the drawing as hex string",
      "type": "array"
    }
  }
}

=== npiccolotto/undrground-tubes/designspace-test/ds_dataset2_60.json
{"glyph_ids": ["designspace-test/./img/ds_dataset2_60_0_thumb.png", "designspace-test/./img/ds_dataset2_60_1_thumb.png", "designspace-test/./img/ds_dataset2_60_2_thumb.png", "designspace-test/./img/ds_dataset2_60_3_thumb.png", "designspace-test/./img/ds_dataset2_60_4_thumb.png", "designspace-test/./img/ds_dataset2_60_5_thumb.png", "designspace-test/./img/ds_dataset2_60_6_thumb.png", "designspace-test/./img/ds_dataset2_60_7_thumb.png", "designspace-test/./img/ds_dataset2_60_8_thumb.png", "designspace-test/./img/ds_dataset2_60_9_thumb.png", "designspace-test/./img/ds_dataset2_60_10_thumb.png", "designspace-test/./img/ds_dataset2_60_11_thumb.png", "designspace-test/./img/ds_dataset2_60_12_thumb.png", "designspace-test/./img/ds_dataset2_60_13_thumb.png", "designspace-test/./img/ds_dataset2_60_14_thumb.png", "designspace-test/./img/ds_dataset2_60_15_thumb.png", "designspace-test/./img/ds_dataset2_60_16_thumb.png", "designspace-test/./img/ds_dataset2_60_17_thumb.png", "designspace-test/./img/ds_dataset2_60_18_thumb.png", "designspace-test/./img/ds_dataset2_60_19_thumb.png", "designspace-test/./img/ds_dataset2_60_20_thumb.png", "designspace-test/./img/ds_dataset2_60_21_thumb.png", "designspace-test/./img/ds_dataset2_60_22_thumb.png", "designspace-test/./img/ds_dataset2_60_23_thumb.png", "designspace-test/./img/ds_dataset2_60_24_thumb.png", "designspace-test/./img/ds_dataset2_60_25_thumb.png", "designspace-test/./img/ds_dataset2_60_26_thumb.png", "designspace-test/./img/ds_dataset2_60_27_thumb.png", "designspace-test/./img/ds_dataset2_60_28_thumb.png", "designspace-test/./img/ds_dataset2_60_29_thumb.png", "designspace-test/./img/ds_dataset2_60_30_thumb.png", "designspace-test/./img/ds_dataset2_60_31_thumb.png", "designspace-test/./img/ds_dataset2_60_32_thumb.png", "designspace-test/./img/ds_dataset2_60_33_thumb.png", "designspace-test/./img/ds_dataset2_60_34_thumb.png", "designspace-test/./img/ds_dataset2_60_35_thumb.png", "designspace-test/./img/ds_dataset2_60_36_thumb.png", "designspace-test/./img/ds_dataset2_60_37_thumb.png", "designspace-test/./img/ds_dataset2_60_38_thumb.png", "designspace-test/./img/ds_dataset2_60_39_thumb.png", "designspace-test/./img/ds_dataset2_60_40_thumb.png", "designspace-test/./img/ds_dataset2_60_41_thumb.png", "designspace-test/./img/ds_dataset2_60_42_thumb.png", "designspace-test/./img/ds_dataset2_60_43_thumb.png", "designspace-test/./img/ds_dataset2_60_44_thumb.png", "designspace-test/./img/ds_dataset2_60_45_thumb.png", "designspace-test/./img/ds_dataset2_60_46_thumb.png", "designspace-test/./img/ds_dataset2_60_47_thumb.png", "designspace-test/./img/ds_dataset2_60_48_thumb.png", "designspace-test/./img/ds_dataset2_60_49_thumb.png", "designspace-test/./img/ds_dataset2_60_50_thumb.png", "designspace-test/./img/ds_dataset2_60_51_thumb.png", "designspace-test/./img/ds_dataset2_60_52_thumb.png", "designspace-test/./img/ds_dataset2_60_53_thumb.png", "designspace-test/./img/ds_dataset2_60_54_thumb.png", "designspace-test/./img/ds_dataset2_60_55_thumb.png", "designspace-test/./img/ds_dataset2_60_56_thumb.png", "designspace-test/./img/ds_dataset2_60_57_thumb.png", "designspace-test/./img/ds_dataset2_60_58_thumb.png", "designspace-test/./img/ds_dataset2_60_59_thumb.png"], "E": ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59"], "EA": [[0.0, 1.3508932470911632, 0.900741514923393, 1.106531697094544, 0.8291865133123594, 1.1732447116178695, 1.205812268937717, 0.6804901751652445, 1.527582313776576, 0.509955987692776, 1.1055358758600844, 1.0737335788942712, 0.7952164960609289, 0.7288291347119285, 0.6169569540896543, 0.534828661911937, 0.6552970859907287, 1.3930426809568897, 0.6988216377044953, 0.2343063372530518, 0.4986938377198733, 0.6516628422105519, 1.0179166987998844, 0.803076404066022, 0.7374399174247521, 1.2003136115215316, 0.770997170218396, 0.8700235570529552, 1.0188092563594215, 1.2555333743451753, 0.7753290454805497, 0.9441569312247062, 1.0846616323293654, 0.9324837007627788, 0.6858422308181805, 0.7626165894877112, 1.3779004242625659, 1.070158210417043, 0.7580218345449757, 1.0496111160680026, 1.0778421222927699, 1.2374448160903548, 1.1006142799942316, 1.0112295829683404, 0.5373315817047044, 0.7336017712171089, 1.3836640174006647, 0.9425776660605631, 0.6094619675486315, 1.0155869751695783, 1.26663717704303, 1.038926300915762, 0.9933506284032713, 0.9426163469010264, 1.188580271837217, 1.1485900693898583, 0.9742242923790587, 1.1171871805495477, 0.8917448622917792, 0.9020326529671667], [1.3508932470911632, 0.0, 1.0102472913548652, 0.8905632188971265, 0.655535287427186, 0.25375060526593124, 0.5079305445248811, 1.056070890778007, 0.750837105387445, 1.0013636069187561, 0.7281181755753987, 0.7016552433462647, 0.7474281583402135, 0.9090202239132271, 1.000977486651585, 0.9812664766792639, 1.123278584423522, 0.20537639570477728, 1.1004020342873302, 1.23063726938776, 0.8905587331557693, 0.8284320281898813, 0.7279532096727075, 0.8685514233184162, 1.1273055540700891, 0.719469180053534, 1.2040614385562596, 1.0105353365337255, 0.7572197793279278, 0.6741060001936053, 0.9031045470173705, 1.1557251225750298, 0.9063316533298312, 0.8184328235460014, 0.8289081244347908, 0.8493320506021337, 0.6961493820694322, 0.6795072378766764, 1.229692703154864, 0.8292310829305612, 1.0430540922596623, 1.0023758984888234, 0.7154686579661713, 0.762777922598117, 1.2622206189108667, 0.9594431409734588, 0.40753550854930476, 0.7083767953939647, 0.9468453712407717, 0.7310306035410321, 0.36682741745941, 0.5318205227220046, 0.5584541755823653, 0.852498441442157, 0.41535887814761996, 0.6265461982212057, 0.8067388305428879, 0.5346110128285506, 0.8450951559881533, 0.8939982821964335], [0.900741514923393, 1.0102472913548652, 0.0, 0.38901681134432575, 0.7684035842104047, 0.9326796839540842, 1.2165977396226983, 0.37475490034698516, 1.0991295964699652, 0.581217143660692, 0.615776673937998, 0.626280426645954, 0.5032767087045112, 1.0228558578156435, 0.7354390190704818, 0.7197324028025736, 0.4799302689590087, 1.0571682798081892, 0.5400330256326116, 0.8918120316118074, 0.803744252407524, 0.40290346724197845, 0.6122169161552239, 0.7593736230144056, 1.096437319230576, 1.0784934903999763, 1.0387361625071398, 1.080559395804469, 1.1207676119701084, 0.7483281632501965, 0.46032551729253834, 0.8039412191985408, 0.7587295277376537, 0.37251540352438167, 0.9694617222237552, 0.36120390008186337, 1.0473031937948682, 0.9658004013845821, 1.199348767673751, 0.6638790148376211, 0.6226434755805281, 0.9442850129603315, 0.46694494911438506, 0.6590978479397069, 0.5768763922765785, 0.8766362814413815, 1.1606649139490546, 1.0515393086774996, 0.6245684295101226, 0.8705327862198214, 0.9412403632284785, 0.7964020642789529, 0.8201295754112197, 0.893361434358477, 0.9686811403667492, 0.9265967425622333, 0.9239009842101102, 0.9174806829701085, 0.9153072219008649, 0.8906423306766459], [1.106531697094544, 0.8905632188971265, 0.38901681134432575, 0.0, 0.6747223445305239, 0.8251961317539745, 1.1192667851308928, 0.6759813196397961, 1.1638077392137964, 0.6515257008864591, 0.7505818176591025, 0.3822020425949394, 0.5139504788304108, 1.15640978606299, 0.9998920682767635, 0.9502019673480162, 0.8316372279332419, 0.9484994399731325, 0.866922178234691, 1.0399753495196915, 0.9060274723383533, 0.5204564252055045, 0.5727410703162165, 0.8865202902270698, 1.2707292064085693, 1.0183375481654138, 1.1573475007992766, 1.2135728717756256, 1.2065179845181389, 0.7376307047516998, 0.6340872008599113, 1.0708610118592268, 0.7538022046010573, 0.6153268120586479, 1.0821444808552143, 0.44673865943244173, 1.141728099314424, 0.7736486747794105, 1.406254363637313, 0.5721965543950155, 0.8825080699968693, 1.1752470777952893, 0.4674953593330172, 0.41171244470574736, 0.8378939941543635, 1.0633062663126442, 1.080721339854144, 1.0344477952892235, 0.8166867964534319, 0.9897540650008941, 0.7294513584701398, 0.7457874996870273, 0.7957004650226897, 1.004326081223683, 0.800759832277264, 0.9282089449939237, 1.0561607137275282, 0.7809294134984136, 1.0497557894489251, 1.006874812349838], [0.8291865133123594, 0.655535287427186, 0.7684035842104047, 0.6747223445305239, 0.0, 0.45226296206631694, 0.5482502114282907, 0.7420734850346749, 1.1211644862075552, 0.4261935880738134, 0.7934604556276025, 0.41764144025308225, 0.3638143122966944, 0.726723008678016, 0.7861473144109964, 0.6789385844270679, 0.8713898981616174, 0.7038863614631667, 0.8633778251268759, 0.6724360205279368, 0.4222748741432005, 0.4461560907741678, 0.528197491084043, 0.6148181067694104, 0.8508945191244258, 0.6432788918296914, 0.8036538793434916, 0.8927206063268024, 0.7432214559053885, 0.7701082231741592, 0.6870841625041018, 1.0147647628960816, 0.6963832608369256, 0.7490235622936015, 0.5705586249324961, 0.5339074031207174, 1.0179001117505402, 0.366375339135142, 0.9881361180065953, 0.5548051782307097, 1.0021874326881062, 1.1415194211313724, 0.7234886765576577, 0.3587428661444209, 0.8746695778859968, 0.7358673804655054, 0.7368544730982605, 0.5589428712609549, 0.5985893409710257, 0.8139560279579857, 0.500291649885104, 0.5421252836522831, 0.5365686976660953, 0.8142169919390027, 0.4670116890923139, 0.7635068686952556, 0.83952581636997, 0.4969216011620283, 0.8006067965853042, 0.8116807673022094], [1.1732447116178695, 0.25375060526593124, 0.9326796839540842, 0.8251961317539745, 0.45226296206631694, 0.0, 0.36938504783458787, 0.9203840509120601, 0.792968750214939, 0.8128487443837562, 0.6691618157322572, 0.5600813499760852, 0.5648050382355957, 0.8218333759936998, 0.8836166030480789, 0.8261549309243875, 1.0253204465958785, 0.25795346267853325, 0.9824131312810814, 1.0261936020499, 0.6936954118024434, 0.7053482420843307, 0.558374321282159, 0.6740753944311866, 0.9359481275242121, 0.5087
